"""
Ptthon script to postprocess tmgl7a output
to make code acceptabe to as7 and PDP-7 tmgl builtins
only handles cases generated by tmgl7a running over itself!
"""

import sys
import re

STR_RE = re.compile("<[^>]*>")

UNPRINT = [ord(x) for x in '\t <\\']
def pr(x):
    if x in UNPRINT:
        return False
    if x <= 0o40 or x > 0o176:
        return False
    return True

end_next = ''
for line in sys.stdin.readlines():
    if end_next:
        if not line.startswith('x '):
            line = end_next + line
        end_next = ''

    # PDP-11 uses bare address for both builtins and TMG code
    # (determines which by address range)
    # need to have a rule that recognizes all builtins???

    line = line.replace("parse", "rf parsedo")
    if 'x rf parsedo' in line:
        end_next = 'x '
        line = line.replace('x rf parsedo', 'rf parsedo')
    line = line.replace("smark", "rf mark")
    line = line.replace("ignore", "rf ign11")
    line = line.replace("octal", "rf octal")
    line = line.replace("any", "rf char")
    line = line.replace("table", "rf tab11")

    # split up string lits
    # wondering if lit strings were dumped out by symoct (in octal)?!
    # OR if PDP-7 TMGL only had two-char lits?
    # OR whether a looping rule with char(nogt) char(nogt) would work
    #   to peel of character pairs?
    if line.startswith('<') and line.endswith('>\n'):
        s = line[1:-2]
        out = []
        while len(s) > 1:
            s0 = s[0]
            s1 = s[1]
            o0 = ord(s0)
            o1 = ord(s1)
            if pr(o0):
                if pr(o1):
                    out.append("<%s%s>" % (s0, s1))
                else:
                    out.append("<%s %03o" % (s0, o1))
            elif pr(o1):
                out.append("%03o000 %s>" % (o0, s1))
            else:
                out.append("%03o%03o" % (o0, o1))
            s = s[2:]
        if len(s) == 1:
            s0 = s[0]
            o0 = ord(s0)
            if pr(o0):
                out.append("<%s 0777" % s0)
            else:
                out.append("%03o777" % o0)
        else:
            out.append('end')
        line = '; '.join(out) + '\n'
    sys.stdout.write(line)
